version: '2'
services:
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    volumes:
    - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: gameday
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
    - 27017:27017